### ISSUE TITLE
Pesquisar sobre os sites institucionais que possuem artigos sobre o coronaVirus: 

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/barra-anti-corona#6]
Que sejam similares a: https://www.saude.ce.gov.br/coronavirus-covid-19/

**Comment by camilaccolares** [comment]
Acre (AC) - http://saude.acre.gov.br/
    
    Alagoas (AL) - http://www.saude.al.gov.br/
    
    Amapá (AP) http://amapa.gov.br/coronavirus
    
    Amazonas (AM) fora do ar
    
    Bahia (BA) www.saude.ba.gov.br/coronavirus
    
    Ceará (CE)
    
    Distrito Federal (DF) http://www.saude.df.gov.br/coronavirus/
    
    Espírito Santo (ES) - www.saude.es.gov.br
    
    Goiás (GO) - banner na página principal com texto "Tire suas duvidas. acesse aqui" http://www.saude.go.gov.br/component/content/article/34-page/9895-coronav%C3%ADrus.html?highlight=WyJjb3JvbmF2XHUwMGVkcnVzIl0=&Itemid=101

    Maranhão (MA) - site principal (http://www.saude.ma.gov.br/) já cai direto em página com texto "Tire suas dúvidas sobre Coronavírus. Clique aqui". Acima há uma barra com o texto "Ir para o site da saúde".

    Mato Grosso (MT) - banner na página principal "Tire suas dúvidas. Acesse aqui". (http://www.saude.mt.gov.br/informe/581)

    Mato Grosso do Sul (MS) - banner na página principal "Tire suas dúvidas. Acesse aqui". (http://www.saude.ms.gov.br/covid-19/)

    Minas Gerais (MG) - banner na página principal informando sobre o site (www.saude.mg.gov.br/coronavirus) e informando um número de whatsapp para mais informações (031) 98272-0553

    Pará (PA) - banner na página principal (http://www.saude.pa.gov.br/coronavirus/)

    Paraíba (PB) - banner bem escondido (lá em baixo) na página principal (https://paraiba.pb.gov.br/diretas/saude/coronavirus/coronavirus)

    Paraná (PR) - banner na página principal com o texto "Acesse o novo site" (http://coronavirus.pr.gov.br/)

    Pernambuco (PE) - foco do site ainda no carnaval. somente noticia na página principal. (www.saude.pe.gov.br)

    Piauí (PI) - no final da página principal há uma área de "Notas e avisos importantes" onde alguns documentos como boletins epidemiológicos, plano de contingência e orientações podem ser baixados. (www.saude.pi.gov.br)

    Rio de Janeiro (RJ) rj.gov.br/coronavirus e www.coronavirusrj.com.br

    Rio Grande do Norte (RN) - botão na página principal (http://www.saude.rn.gov.br/Conteudo.asp?TRAN=ITEM&TARG=223456&ACT=&PAGE=&PARM=&LBL=MAT%C9RIA
    )
    Rio Grande do Sul (RS) - botão na página principal (https://saude.rs.gov.br/covid-19)

    Rondônia (RO) - botão na página principal (http://www.rondonia.ro.gov.br/agevisa/institucional/coronavirus/)

    Roraima (RR) - banner na página principal (https://www.saude.rr.gov.br/index.php/informacoesx/coronavirus/informacoes-coronavirus)

    Santa Catarina (SC) - banner na página principal (http://www.saude.sc.gov.br/coronavirus/)

    São Paulo (SP) - banner na página principal (http://saopaulo.sp.gov.br/coronavirus/)
    
    Sergipe (SE) - banner na página principal (https://www.saude.se.gov.br/?p=38287)

    Tocantins (TO) - botão de serviços em destaque (https://saude.to.gov.br/cievs---centro-de-informacoes-estrategicas-de-vigilancia-em-saude/coronavirus-covid-19/)
